### ISSUE TITLE
Architecture aarch64 not working

### ISSUE THREAD

**Issue by Benjamin-K** [Flowpack/Flowpack.Prunner#10]
When using a machine with architecture `aarch64`, which is simply another name for `arm64`, the post-package-install script will throw an exception. Therefore the architecture `aarch64` should simply be replaced with `arm64` in [Classes/Composer/InstallerScripts.php](../blob/main/Classes/Composer/InstallerScripts.php)

**Comment by Benjamin-K** [comment]
Oh, i saw that @skurfuerst has already addressed this issue but there is no new release yet. Could you create a new version with the fix made in the last commit?

**Comment by skurfuerst** [comment]
Fixed now, or did I miss anything? :)
